-- ============================================================================
-- 1. CADASTROS BASE (ENTIDADES INDEPENDENTES)
-- ============================================================================

-- Cadastro de Planos de Saúde / Convênios
CREATE TABLE convenio (
    cnpj VARCHAR(14) NOT NULL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
);

-- Cadastro de Fisioterapeutas / Terapeutas / Instrutores
CREATE TABLE profissional (
    profissional_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    crefito_ou_registro VARCHAR(20) UNIQUE NOT NULL,
    telefone VARCHAR(15) NOT NULL
);

-- Tabela Única de Modalidades / Serviços Prestados
CREATE TABLE modalidade (
    modalidade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL, -- Ex: 'Fisioterapia', 'Pilates', 'RPG', 'Massagem', 'Liberação'
    duracao_minutos INT NOT NULL DEFAULT 50,
    valor_base DECIMAL(10,2) NOT NULL
);

-- ============================================================================
-- 2. CADASTROS DEPENDENTES (ENTIDADES COM CHAVES ESTRANGEIRAS)
-- ============================================================================

-- Cadastro Unificado de Clientes/Pacientes
CREATE TABLE cliente (
    cpf VARCHAR(11) NOT NULL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    convenio_id INT REFERENCES convenio(convenio_id) ON DELETE SET NULL,
    numero_carteirinha VARCHAR(50),
    status_clinico VARCHAR(20) DEFAULT 'ATIVO' CHECK (status_clinico IN ('ATIVO', 'INATIVO'))
);

-- Central Única de Sessões (Agenda, Atendimento e Fluxo Operacional)
CREATE TABLE sessao (
    sessao_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES cliente(cliente_id) ON DELETE CASCADE,
    profissional_id INT NOT NULL REFERENCES profissional(profissional_id),
    modalidade_id INT NOT NULL REFERENCES modalidade(modalidade_id),
    data_hora_inicio TIMESTAMP NOT NULL,
    data_hora_fim TIMESTAMP NOT NULL,
    sessao_tipo VARCHAR(25) NOT NULL
        CHECK (sessao_tipo IN ('AVALIACAO_INICIAL', 'TRATAMENTO_ROTINA', 'REAVALIACAO')),
    pagamento_origem VARCHAR(20) NOT NULL
        CHECK (pagamento_origem IN ('PARTICULAR', 'CONVENIO')),
    sessao_status VARCHAR(20) NOT NULL DEFAULT 'AGENDADA'
        CHECK (sessao_status IN ('AGENDADA', 'CONFIRMADA', 'REALIZADA', 'FALTOU', 'CANCELADA')),
    observacoes_recepcao TEXT
);

-- ============================================================================
-- 3. MÓDULO CLÍNICO (EVOLUÇÃO E PRONTUÁRIO)
-- ============================================================================

-- Prontuário / Registro Clínico da Sessão (1:1 com Sessão)
CREATE TABLE sessao_prontuario (
    prontuario_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id INT UNIQUE NOT NULL REFERENCES sessao(sessao_id) ON DELETE CASCADE,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    queixa_subjetiva TEXT,          -- Relato do cliente (Escala de dor, sintomas)
    avaliacao_objetiva TEXT,         -- Testes físicos e palpação (crucial em AVALIACAO)
    conduta_procedimento TEXT,      -- O que foi executado (Exercícios, manipulações)
    plano_orientacoes TEXT          -- Recomendações para casa ou próximos passos
);

-- ============================================================================
-- 4. MÓDULO FINANCEIRO (BILLING E FLUXO DE CAIXA)
-- ============================================================================

-- Cabeçalho do Faturamento (A Fatura / Conta gerada para o Cliente ou Convênio)
CREATE TABLE faturamento (
    faturamento_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES cliente(cliente_id) ON DELETE CASCADE,
    pagamento_origem VARCHAR(20) NOT NULL CHECK (pagamento_origem IN ('PARTICULAR', 'CONVENIO')),
    convenio_id INT REFERENCES convenio(convenio_id) ON DELETE SET NULL,
    valor_total_faturado DECIMAL(10,2) NOT NULL,
    data_emissao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    faturamento_status VARCHAR(20) NOT NULL DEFAULT 'ABERTO'
        CHECK (faturamento_status IN ('ABERTO', 'CONSOLIDADO', 'CANCELADO')),
    observacoes TEXT
);

-- Itens do Faturamento (Vincula quais sessões estão sendo cobradas na fatura)
CREATE TABLE faturamento_item (
    faturamento_id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faturamento_id INT NOT NULL REFERENCES faturamento(faturamento_id) ON DELETE CASCADE,
    sessao_id INT UNIQUE NOT NULL REFERENCES sessao(sessao_id) ON DELETE RESTRICT, -- Impede deletar sessão faturada
    valor_item DECIMAL(10,2) NOT NULL
);

-- Parcelas de Recebimento (Fluxo de Caixa real associado ao faturamento)
CREATE TABLE recebimento_parcela (
    parcela_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faturamento_id INT NOT NULL REFERENCES faturamento(faturamento_id) ON DELETE CASCADE,
    numero_parcela INT NOT NULL DEFAULT 1,
    valor_parcela DECIMAL(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    pagamento_status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
        CHECK (pagamento_status IN ('PENDENTE', 'PAGO', 'GLOSADO_CONVENIO', 'ATRASADO')),
    data_pagamento TIMESTAMP,
    pagamento_meio VARCHAR(30)
        CHECK (pagamento_meio IN ('DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX', 'TRANSFERENCIA', 'FATURA_CONVENIO'))
);
