drop table if exists fisio.sessao_prontuario cascade;
drop table if exists fisio.sessao cascade;
drop table if exists fisio.cliente cascade;
drop table if exists fisio.modaliade cascade;
drop table if exists fisio.profisional cascade;
drop table if exists fisio.convenio cascade;

-- Cadastro de Planos de Saúde / Convênios
CREATE TABLE fisio.convenio (
    convenio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(14) NOT NULL,
    nome VARCHAR(100) NOT NULL
);

-- Cadastro de Fisioterapeutas / Terapeutas / Instrutores
CREATE TABLE fisio.profissional (
    profissional_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    crefito_ou_registro VARCHAR(20) UNIQUE NOT NULL,
    telefone VARCHAR(15) NOT NULL
);

-- Tabela Única de Modalidades / Serviços Prestados
CREATE TABLE fisio.modalidade (
    modalidade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL, -- Ex: 'Fisioterapia', 'Pilates', 'RPG', 'Massagem', 'Liberação'
    duracao_minutos INT NOT NULL DEFAULT 50,
    valor_base DECIMAL(10,2) NOT NULL
);

-- Cadastro Unificado de Clientes/Pacientes
CREATE TABLE fisio.cliente (
    cliente_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    convenio_id INT REFERENCES convenio(convenio_id),
    numero_carteirinha VARCHAR(50),
    status_clinico VARCHAR(20) DEFAULT 'ATIVO' CHECK (status_clinico IN ('ATIVO', 'INATIVO'))
);

-- Central Única de Sessões (Agenda, Atendimento e Fluxo Operacional)
CREATE TABLE fisio.sessao (
    sessao_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES cliente(cliente_id),
    profissional_id INT NOT NULL REFERENCES profissional(profissional_id),
    modalidade_id INT NOT NULL REFERENCES modalidade(modalidade_id),
    data_hora_inicio TIMESTAMP NOT NULL,
    data_hora_fim TIMESTAMP NOT NULL,
    tipo_sessao VARCHAR(25) NOT NULL
        CHECK (tipo_sessao IN ('AVALIACAO_INICIAL', 'TRATAMENTO_ROTINA', 'REAVALIACAO')),
    tipo_pagamento VARCHAR(20) NOT NULL
        CHECK (tipo_pagamento IN ('PARTICULAR', 'CONVENIO')),
    status_sessao VARCHAR(20) NOT NULL DEFAULT 'AGENDADA'
        CHECK (status_sessao IN ('AGENDADA', 'CONFIRMADA', 'REALIZADA', 'FALTOU', 'CANCELADA')),
    observacoes_recepcao TEXT
);

-- Prontuário / Registro Clínico da Sessão (1:1 com Sessão)
CREATE TABLE fisio.sessao_prontuario (
    prontuario_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id INT NOT NULL REFERENCES sessao(sessao_id),
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    queixa_subjetiva TEXT,          -- Relato do cliente (Escala de dor, sintomas)
    avaliacao_objetiva TEXT,         -- Testes físicos e palpação (crucial em AVALIACAO)
    conduta_procedimento TEXT,      -- O que foi executado (Exercícios, manipulações)
    plano_orientacoes TEXT          -- Recomendações para casa ou próximos passos
);