drop table if exists fisio.recebimento_parcela cascade;
drop table if exists fisio.faturamento_item cascade;
drop table if exists fisio.faturamento cascade;

-- Cabeçalho do Faturamento (A Fatura / Conta gerada para o Cliente ou Convênio)
CREATE TABLE fisio.faturamento (
    faturamento_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INT NOT NULL REFERENCES cliente(cliente_id),
    tipo_faturamento VARCHAR(20) NOT NULL CHECK (tipo_faturamento IN ('PARTICULAR', 'CONVENIO')),
    convenio_id INT REFERENCES convenio(convenio_id),
    valor_total_faturado DECIMAL(10,2) NOT NULL,
    data_emissao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_faturamento VARCHAR(20) NOT NULL DEFAULT 'ABERTO'
        CHECK (status_faturamento IN ('ABERTO', 'CONSOLIDADO', 'CANCELADO')),
    observacoes TEXT
);

-- Itens do Faturamento (Vincula quais sessões estão sendo cobradas na fatura)
CREATE TABLE fisio.faturamento_item (
    faturamento_id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faturamento_id INT NOT NULL REFERENCES faturamento(faturamento_id),
    sessao_id INT UNIQUE NOT NULL REFERENCES sessao(sessao_id),
    valor_item DECIMAL(10,2) NOT NULL
);

-- Parcelas de Recebimento (Fluxo de Caixa real associado ao faturamento)
CREATE TABLE fisio.recebimento_parcela (
    parcela_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faturamento_id INT NOT NULL REFERENCES faturamento(faturamento_id),
    numero_parcela INT NOT NULL DEFAULT 1,
    valor_parcela DECIMAL(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    status_pagamento VARCHAR(20) NOT NULL DEFAULT 'PENDENTE'
        CHECK (status_pagamento IN ('PENDENTE', 'PAGO', 'GLOSADO_CONVENIO', 'ATRASADO')),
    data_pagamento TIMESTAMP,
    forma_pagamento VARCHAR(30)
        CHECK (forma_pagamento IN ('DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX', 'TRANSFERENCIA', 'FATURA_CONVENIO'))
);
